apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: rook-ceph-admin-keyring
  namespace: rook-ceph
spec:
  vaultAuthRef: static-auth
  mount: secret
  path: rook-ceph/admin-keyring
  refreshAfter: 1m
  destination:
    name: rook-ceph-admin-keyring
    create: true
