apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: rook-ceph-admin-keyring
  namespace: rook-ceph
spec:
  type: kv-v2
  refreshAfter: 30s
  vaultAuthRef: static-auth

  # Things to change:
  mount: isis-compute-cluster
  path: admin-keyring
  destination:
    name: rook-ceph-admin-keyring
    overwrite: true
    create: true