#---
#apiVersion: argoproj.io/v1alpha1
#kind: Application
#metadata:
#  name: grafana
#  namespace: argocd
#  annotations:
#    argocd.argoproj.io/sync-wave: "0"
#spec:
#  project: default
#  sources:
#  - repoURL: https://grafana.github.io/helm-charts
#    targetRevision: 12.10.4
#    chart: grafana
#    helm:
#      valueFiles:
#      - $values/compute-cluster/gitops/apps/loki/values.yml
#  - repoURL: git@github.com:ISISNeutronMuon/MNeuData.git
#    targetRevision: compute_cluster
#    ref: values
#  - repoURL: git@github.com:ISISNeutronMuon/MNeuData.git
#    targetRevision: compute_cluster
#    path: compute-cluster/gitops/components/loki
#  destination:
#    namespace: grafana
#    server: https://kubernetes.default.svc
#  syncPolicy:
#    automated:
#      prune: true
#      selfHeal: true
#    syncOptions:
#      - ServerSideApply=true
#      - CreateNamespace=true