apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: local-path-provisioner
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: infra
  sources:
  - repoURL: https://github.com/rancher/local-path-provisioner.git
    targetRevision: v0.0.37
    path: deploy/chart/local-path-provisioner
    helm:
      valueFiles:
      - $values/compute-cluster/gitops/apps/local-path-provisioner/values.yml
  - repoURL: git@github.com:ISISNeutronMuon/MNeuData.git
    targetRevision: compute_cluster
    ref: values
  - repoURL: git@github.com:ISISNeutronMuon/MNeuData.git
    targetRevision: compute_cluster
    path: compute-cluster/gitops/components/local-path-provisioner
  destination:
    server: https://kubernetes.default.svc
    namespace: local-path-storage
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
