apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: gateway-cert
  namespace: envoy-gateway-system
spec:
  secretName: compute-tls
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
  dnsNames:
  - compute.isis.cclrc.ac.uk
  - argo.compute.isis.cclrc.ac.uk
  - hubble.compute.isis.cclrc.ac.uk
  - s3.compute.isis.cclrc.ac.uk
  - s3-admin.compute.isis.cclrc.ac.uk
  - versity.compute.isis.cclrc.ac.uk
  - loki.compute.isis.cclrc.ac.uk
  - mimir.compute.isis.cclrc.ac.uk
  - tempo.compute.isis.cclrc.ac.uk
  - grafana.compute.isis.cclrc.ac.uk
