---
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: smb.csi.k8s.io
  name: s3-backend-pv
spec:
  capacity:
    storage: 4000Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
#    - sec=ntlmssp   # Try ntlmssp or ntlmv2 to resolve error 126
    - vers=3.0      # Enforce SMB 3.0 (or 2.1 depending on host support)
  csi:
    driver: smb.csi.k8s.io
    volumeHandle: s3-backend-1
    volumeAttributes:
      source: "//ISIS.cclrc.ac.uk/Shares"
      subDir: "MNeudataCC/s3-backend"
    nodeStageSecretRef:
      name: smb-creds
      namespace: kube-system