---
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: smb.csi.k8s.io
  name: s3-backend-pv
spec:
  capacity:
    storage: 4000Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: smb.csi.k8s.io
    volumeHandle: s3-backend
    volumeAttributes:
      source: "//ISIS.cclrc.ac.uk/Shares/MNeudataCC/s3-backend"
    nodeStageSecretRef:
      name: smb-creds
      namespace: kube-system