apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: s3-backend
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 4000Gi
  volumeName: s3-backend-pv
  storageClassName: ""