apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: smb.csi.k8s.io
  name: s3-backend-pv
spec:
  capacity:
    storage: 4000Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - dir_mode=0775
    - file_mode=0774
    - gid=1000
    - iocharset=utf8
  csi:
    driver: smb.csi.k8s.io
    volumeHandle: s3-backend-v3
    volumeAttributes:
      # Possible that the share could migrate on the backend, DFS does not work within Talos, or linux more generally
      # (Works with an OS level hack on Linux but does not work on Talos at all)
      source: "//ISISFS-ExpData2.isis.cclrc.ac.uk/MNeudataCC$"
      subDir: "s3-backend"
    nodeStageSecretRef:
      name: smb-creds
      namespace: kube-system