image:
  repository: ghcr.io/versity/versitygw
  tag: "v1.2.0"

gateway:
  backend:
    type: "posix"
    args: "/mnt/data"

auth:
  existingSecret: "versity-s3-root"

ingress:
  enabled: false

httpRoute:
  enabled: true
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: gateway
      namespace: kube-system
  hostnames:
    - "compute.isis.cclrc.ac.uk"
  rules:
    - matches:
        - path:
            type: "PathPrefix"
            value: "/s3"
      filters:
        - type: URLRewrite
          urlRewrite:
            path:
              type: ReplacePrefixMatch
              replacePrefixMatch: "/"

webui:
  enabled: true
  httpRoute:
    enabled: true
    parentRefs:
      - group: gateway.networking.k8s.io
        kind: Gateway
        name: gateway
        namespace: kube-system
    hostnames:
      - "compute.isis.cclrc.ac.uk"
    rules:
      - matches:
          - path:
              type: "PathPrefix"
              value: "/versityui"
        filters:
          - type: URLRewrite
            urlRewrite:
              path:
                type: ReplacePrefixMatch
                replacePrefixMatch: "/"

persistence:
  enabled: true
  create: false
  claimName: s3-backend