#apiVersion: argoproj.io/v1alpha1
#kind: Application
#metadata:
#  name: rabbitmq
#  namespace: argocd
#  finalizers:
#  - resources-finalizer.argocd.argoproj.io
#spec:
#  project: infra
#  source:
#    repoURL: https://github.com/ISISNeutronMuon/MNeuData.git
#    targetRevision: compute_cluster
#    path: gitops/components/rabbitmq
#  destination:
#    server: https://kubernetes.default.svc
#    namespace: rabbitmq-system
#  syncPolicy:
#    automated:
#      prune: true
#      selfHeal: true
#    syncOptions:
#    - CreateNamespace=true
