apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: argocd-route
  namespace: argocd
spec:
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: gateway
    namespace: kube-system
  hostnames:
  - compute.isis.cclrc.ac.uk
  rules:
  - matches:
    - path:
        type: Exact
        value: /argocd
    filters:
    - type: RequestRedirect
      requestRedirect:
        path:
          replaceFullPath: /argocd/
        statusCode: 301
  - matches:
    - path:
        type: PathPrefix
        value: /argocd
    backendRefs:
    - group: ""
      kind: Service
      name: argocd-server
      port: 80
      weight: 1
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: hubble-route
  namespace: kube-system
spec:
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: gateway
    namespace: kube-system
  hostnames:
  - compute.isis.cclrc.ac.uk
  rules:
  - matches:
    - path:
        type: Exact
        value: /hubble
    filters:
    - type: RequestRedirect
      requestRedirect:
        path:
          replaceFullPath: /hubble/
        statusCode: 301
  - matches:
    - path:
        type: PathPrefix
        value: /hubble
    backendRefs:
    - group: ""
      kind: Service
      name: hubble-ui
      port: 80
      weight: 1
