apiVersion: v1
kind: ConfigMap
metadata:
  name: s3-exporter-aws-config
  namespace: monitoring-system
  labels:
    app.kubernetes.io/name: s3-exporter
data:
  config: |
    [default]
    s3 =
        addressing_style = path
