apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: s3-exporter
  namespace: monitoring-system
  labels:
    app.kubernetes.io/name: s3-exporter
spec:
  endpoints:
  - port: metrics
    path: /metrics
    interval: 60s
    scrapeTimeout: 10s
    scheme: http
  jobLabel: app.kubernetes.io/name
  namespaceSelector:
    matchNames:
    - monitoring-system
  selector:
    matchLabels:
      app.kubernetes.io/name: s3-exporter
