all:
  vars:
    ansible_connection: local
  children:
    control_plane:
      hosts:
        cp1:
          ansible_host: 130.246.55.77
        cp2:
          ansible_host: 130.246.55.45
        cp3:
          ansible_host: 130.246.55.68
    worker:
      hosts:
        w1:
          ansible_host: 130.246.55.57
        w2:
          ansible_host: 130.246.55.51
        w3:
          ansible_host: 130.246.55.67
