apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres-cluster
  namespace: postgres-system
spec:
  instances: 3
  imageName: ghcr.io/cloudnative-pg/postgresql:17.2
  storage:
    size: 10Gi
    storageClass: smb-postgres
  bootstrap:
    initdb:
      database: grafana
      owner: grafana
      secret:
        name: grafana-db-user
  postgresql:
    parameters:
      wal_level: logical
