apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: grafana-db-user
  namespace: postgres-system
spec:
  type: kv-v2
  refreshAfter: 30s
  vaultAuthRef: static-auth

  mount: isis-compute-cluster
  path: grafana/host/database
  destination:
    name: grafana-db-user
    type: kubernetes.io/basic-auth
    overwrite: true
    create: true
