apiVersion: postgresql.cnpg.io/v1
kind: Publication
metadata:
  name: all-tables-pub
  namespace: postgres-system
spec:
  cluster:
    name: postgres-cluster
  name: all_tables
  target:
    allTables: true
