apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: longhorn-backup-secret
  namespace: longhorn-system
spec:
  type: kv-v2
  refreshAfter: 30s
  vaultAuthRef: static-auth

  mount: isis-compute-cluster
  path: longhorn-backup-secret
  destination:
    name: longhorn-backup-secret
    overwrite: true
    create: true