apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: versitygw
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: infra
  sources:
  - repoURL: git@github.com:ISISNeutronMuon/MNeuData.git
    targetRevision: compute_cluster
    path: compute-cluster/gitops/components/versitygw
    # Enable Helm inflation inside Kustomize
    kustomize:
      buildOptions: "--enable-helm"
  destination:
    server: https://kubernetes.default.svc
    namespace: versitygw-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true