image:
  repository: ghcr.io/versity/versitygw
  tag: "v1.2.0"

gateway:
  backend:
    type: "posix"
    args: "/mnt/data"

auth:
  existingSecret: "versity-s3-root"

httpRoute:
  enabled: true
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: gateway
      namespace: kube-system
  hostnames:
    - "s3.compute.isis.cclrc.ac.uk"

webui:
  enabled: true
  apiGateways:
    - "https://s3.compute.isis.cclrc.ac.uk"
  adminGateways:
    - "https://s3-admin.compute.isis.cclrc.ac.uk"
  httpRoute:
    enabled: true
    parentRefs:
      - group: gateway.networking.k8s.io
        kind: Gateway
        name: gateway
        namespace: kube-system
    hostnames:
      - "versity.compute.isis.cclrc.ac.uk"

admin:
  enabled: true
  httpRoute:
    enabled: true
    parentRefs:
      - group: gateway.networking.k8s.io
        kind: Gateway
        name: gateway
        namespace: kube-system
    hostnames:
      - "s3-admin.compute.isis.cclrc.ac.uk"

persistence:
  enabled: true
  create: false
  claimName: s3-backend