image:
  repository: ghcr.io/versity/versitygw
  tag: "v1.2.0"

gateway:
  backend:
    type: "posix"
    args: "/mnt/data"

auth:
  existingSecret: "versity-s3-root"

httpRoute:
  enabled: false

webui:
  enabled: true
  apiGateways:
    - "https://s3.compute.isis.cclrc.ac.uk"
  adminGateways:
    - "https://s3-admin.compute.isis.cclrc.ac.uk"
  httpRoute:
    enabled: false

admin:
  enabled: true
  httpRoute:
    enabled: false

persistence:
  enabled: true
  create: false
  claimName: s3-backend