apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: versity-s3-root
  namespace: loki
spec:
  type: kv-v2
  refreshAfter: 30s
  vaultAuthRef: static-auth

  mount: isis-compute-cluster
  path: versity-s3-root
  destination:
    name: versity-s3-root
    overwrite: true
    create: true