cluster:
  name: mneudata-compute

destinations:
  metrics-service:
    type: prometheus
    url: https://mimir.compute.isis.cclrc.ac.uk/mneudata-compute/api/v1/push
    auth:
      type: basic
      usernameKey: username
      passwordKey: password
    secret:
      create: false
      name: mimir-basic-auth
      namespace: monitoring-system
    tls:
      insecureSkipVerify: true

  logs-service:
    type: loki
    url: https://loki.compute.isis.cclrc.ac.uk/mneudata-compute/loki/api/v1/push
    auth:
      type: basic
      usernameKey: username
      passwordKey: password
    secret:
      create: false
      name: loki-basic-auth
      namespace: monitoring-system
    tls:
      insecureSkipVerify: true

  traces-service:
    type: otlp
    protocol: http
    url: https://tempo.compute.isis.cclrc.ac.uk/mneudata-compute
    auth:
      type: basic
      usernameKey: username
      passwordKey: password
    secret:
      create: false
      name: tempo-basic-auth
      namespace: monitoring-system
    metrics:
      enabled: true
    logs:
      enabled: true
    traces:
      enabled: true
    tls:
      insecureSkipVerify: true

annotationAutodiscovery:
  enabled: true
  collector: alloy-singleton
  namespaces: &monitored_namespaces [argocd, cert-manager, default, envoy-gateway-system, grafana, local-path-storage, loki, mimir, monitoring-system, postgres-system, tempo, vault-secrets-operator-system, versitygw-system]

applicationObservability:
  enabled: true
  collector: alloy-receiver
  receivers:
    otlp:
      grpc:
        enabled: true
        port: 4317
      http:
        enabled: true
        port: 4318
  metrics:
    filters:
      metric:
        - 'IsMatch(resource.attributes["k8s.namespace.name"], "^(argocd|cert-manager|default|envoy-gateway-system|grafana|local-path-storage|loki|mimir|monitoring-system|postgres-system|tempo|vault-secrets-operator-system|versitygw-system)$")'
  logs:
    filters:
      log_record:
        - 'IsMatch(resource.attributes["k8s.namespace.name"], "^(argocd|cert-manager|default|envoy-gateway-system|grafana|local-path-storage|loki|mimir|monitoring-system|postgres-system|tempo|vault-secrets-operator-system|versitygw-system)$")'
  traces:
    filters:
      span:
        - 'IsMatch(resource.attributes["k8s.namespace.name"], "^(argocd|cert-manager|default|envoy-gateway-system|grafana|local-path-storage|loki|mimir|monitoring-system|postgres-system|tempo|vault-secrets-operator-system|versitygw-system)$")'

autoInstrumentation:
  enabled: false

clusterEvents:
  enabled: true
  collector: alloy-singleton
  namespaces: *monitored_namespaces

clusterMetrics:
  enabled: true
  collector: alloy-metrics
  cadvisor:
    metricsTuning:
      includeNamespaces: *monitored_namespaces
  kube-state-metrics:
    namespaces: *monitored_namespaces

hostMetrics:
  enabled: true
  collector: alloy-metrics

podLogsViaLoki:
  enabled: true
  collector: alloy-logs
  namespaces: *monitored_namespaces

profiling:
  enabled: false

prometheusOperatorObjects:
  enabled: true
  collector: alloy-metrics
  probes:
    namespaces: *monitored_namespaces
  podMonitors:
    namespaces: *monitored_namespaces
  serviceMonitors:
    namespaces: *monitored_namespaces

telemetryServices:
  kube-state-metrics:
    deploy: true
  node-exporter:
    deploy: true

collectors:
  alloy-metrics:
    presets:
      - clustered
      - statefulset
  alloy-singleton:
    presets:
      - singleton
  alloy-logs:
    presets:
      - daemonset
      - filesystem-log-reader
  alloy-receiver:
    presets:
      - deployment
      - otel-receiver
    alloy:
      extraPorts:
        - name: otlp-grpc
          port: 4317
          targetPort: 4317
          protocol: TCP
        - name: otlp-http
          port: 4318
          targetPort: 4318
          protocol: TCP
