apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: event-udp-to-kafka
  namespace: epics-test
  labels:
    app.kubernetes.io/name: event-udp-to-kafka
spec:
  endpoints:
  - port: metrics
    path: /metrics
    interval: 60s
    scrapeTimeout: 10s
    scheme: http
  jobLabel: app.kubernetes.io/name
  namespaceSelector:
    matchNames:
    - epics-test
  selector:
    matchLabels:
      app.kubernetes.io/name: event-udp-to-kafka
