apiVersion: v1
kind: Service
metadata:
  name: event-udp-to-kafka
  namespace: epics-test
  labels:
    app.kubernetes.io/name: event-udp-to-kafka
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: event-udp-to-kafka
  ports:
  - name: metrics
    port: 8485
    targetPort: metrics
    protocol: TCP
